spring.application.name=taskmanager
# ─── Server ───────────────────────────────────────────
server.port=8080

# ─── SQL Server Database Connection ───────────────────
spring.datasource.url=jdbc:sqlserver://localhost:1433;instanceName=SQLEXPRESS;databaseName=taskflow;encrypt=true;trustServerCertificate=true
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ─── JPA / Hibernate ──────────────────────────────────
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.properties.hibernate.format_sql=true

# ─── JWT ──────────────────────────────────────────────
jwt.secret=taskflow_super_secret_key_rishab_2024_do_not_share
jwt.expiration=86400000
